"""productos

Revision ID: 1deaeb5264cc
Revises: e1b495af6507
Create Date: 2024-05-20 22:37:33.522671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1deaeb5264cc'
down_revision = 'e1b495af6507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('descripcion', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categoria_descripcion'), ['descripcion'], unique=False)
        batch_op.create_index(batch_op.f('ix_categoria_nombre'), ['nombre'], unique=False)

    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('descripcion', sa.String(length=64), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('categoria', sa.String(length=64), nullable=True),
    sa.Column('categoriaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoriaId'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producto_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_descripcion'), ['descripcion'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_precio'), ['precio'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_producto_precio'))
        batch_op.drop_index(batch_op.f('ix_producto_nombre'))
        batch_op.drop_index(batch_op.f('ix_producto_descripcion'))
        batch_op.drop_index(batch_op.f('ix_producto_categoria'))

    op.drop_table('producto')
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categoria_nombre'))
        batch_op.drop_index(batch_op.f('ix_categoria_descripcion'))

    op.drop_table('categoria')
    # ### end Alembic commands ###
