"""Corrección de modelo Factura

Revision ID: 578922c2191e
Revises: 6986c1400185
Create Date: 2024-07-26 05:25:11.973260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578922c2191e'
down_revision = '6986c1400185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factura_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factura_producto')
    # ### end Alembic commands ###
