"""agregar estado del pedido 

Revision ID: 690ea0a62987
Revises: 17fc794344a4
Create Date: 2024-07-30 09:49:08.327649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690ea0a62987'
down_revision = '17fc794344a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_factura_estado'), ['estado'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factura_estado'))
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
