"""agregar numero pedido 

Revision ID: 96df25e775b9
Revises: 9f27d490db42
Create Date: 2024-07-26 06:49:45.884464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96df25e775b9'
down_revision = '9f27d490db42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factura', schema=None) as batch_op:
        # Agregar la columna permitiendo valores nulos
        batch_op.add_column(sa.Column('numero_pedido', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.drop_column('numero_pedido')
    # ### end Alembic commands ###


    # ### end Alembic commands ###
