"""Agregado campo precio descuento

Revision ID: e3247ed62ee6
Revises: c84cbfaa89c3
Create Date: 2024-12-02 20:31:01.643969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3247ed62ee6'
down_revision = 'c84cbfaa89c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descuento', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('descuento')

    # ### end Alembic commands ###
