"""cambiar al correo

Revision ID: ff1f239b611f
Revises: 4484deddd9b0
Create Date: 2024-07-30 11:05:16.204547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1f239b611f'
down_revision = '4484deddd9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo_usuario', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('notificacion_usuario_id_fkey', type_='foreignkey')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('notificacion_usuario_id_fkey', 'user', ['usuario_id'], ['id'])
        batch_op.drop_column('correo_usuario')

    # ### end Alembic commands ###
